### ISSUE TITLE
"Include Document Start" option is broken

### ISSUE THREAD

**Issue by CH-DrewWatson** [longkai/kubernetes-yaml-formatter#10]
I'm running current version in VSCode (1.1.0).

Both checked and unchecked, the "Include Document Start" option is removing the pre-existing "---" from the beginning of all my yaml files.

I'd like for this extension to add the "---" when it's missing, but more importantly, I don't want it to be removed when it's already there.

Otherwise, this extension is helpful for standardizing all my manifests, thank you!

**Comment by CH-DrewWatson** [comment]
While what I mentioned above is true, it appears that from settings GUI, changing the setting does not create the entry in settings.json. This is most likely related to [Issue #7](https://github.com/longkai/kubernetes-yaml-formatter/issues/7), as writing out the setting ("kubernetes-yaml-formatter.includeDocumentStart": true) seems to have fixed the behavior.

**Comment by etutuit** [comment]
Changing setting in GUI creates entry in settings.json, but it creates `"includeDocumentStart": true` instead of `"kubernetes-yaml-formatter.includeDocumentStart": true`.

**Comment by longkai** [comment]
Hi!

Sorry for the delay.

The new v2 version which will release soon will have more controls on including directives in the output format.

**Comment by longkai** [comment]
The v2 version has been released on VSCode and fix this issue.

Give it a try!
