### ISSUE TITLE
Disabling "Use compact sequence indent" has no effect

### ISSUE THREAD

**Issue by justinmchase** [longkai/kubernetes-yaml-formatter#11]
I have disabled "Use compact sequence indent" but when I format the document it still dedents everything.

![image](https://user-images.githubusercontent.com/10974/230653409-843eaf6d-ecfe-4ab6-9bdf-09ab9011f496.png)

**Comment by etutuit** [comment]
Changing this setting in GUI creates `"compactSequenceIndent": false` entry in settings.json instead of mentioned `"kubernetes-yaml-formatter.compactSequenceIndent": false`.

**Comment by longkai** [comment]
Hi!

Sorry for the delay. The new v2 version will have more fine settings and bug fixes.

Hope you will find it useful.
