### ISSUE TITLE
Not register as formatter for Ansible tasks and playbooks

### ISSUE THREAD

**Issue by ICHx** [longkai/kubernetes-yaml-formatter#13]
When Code is opening yaml as Ansible, the formatter is not selectable.

This is shown when I am overriding the [Ansible] editor formatter. 

<img width="296" alt="image" src="https://github.com/longkai/kubernetes-yaml-formatter/assets/11556527/afac8e04-3821-4bb4-84f0-3257a244fd1e">

**Comment by marcselis** [comment]
Same problem. 
After installing the extension, VSCode still says there is no formatter installed for Ansible files.

**Comment by longkai** [comment]
The v2 version has been released on VSCode and fix this issue.

Give it a try!
