### ISSUE TITLE
Do not convert emoji

### ISSUE THREAD

**Issue by kpocius** [longkai/kubernetes-yaml-formatter#2]
Not sure if this is a bug or a feature request and whether it's actually an issue with the upstream, but the extension messes with the code if there are emojis in it.

For example:
```
- test: |
    🔥
```
Becomes:
```
- test: "\U0001F525\n"
```

This is particularly a problem if you have complex scripts that include emojis -- it converts the entire thing into a single-line string.

**Comment by longkai** [comment]
Thanks for the feedback!

I investigated and found there is a bug from the [upstream library](https://github.com/google/yamlfmt/issues/62). It should be fixed and let's see.

**Comment by longkai** [comment]
Just released 1.1.0 to the marketplace, thanks for the feedback!
