### ISSUE TITLE
Upgrade to 2.0 breaks YAMLS with Longer Strings by Splitting them onto a Following Line

### ISSUE THREAD

**Issue by maplion** [longkai/kubernetes-yaml-formatter#22]
I have been using this extension for a while, without issue, but the recent upgrade to 2.0 causes problems where their weren't problems before.

I have CodeUris in an AWS template.yml that when upgraded to 2.0, it splits the string onto a separate line.

For example:

```yml
CodeUri: "s3://#{bucketName}/#{Octopus.Action[Upload Lambda to S3].Output.Package.FileName}"
```

On save, this autoformat changes to:

```yml
CodeUri: "s3://#{bucketName}/#{Octopus.Action[Upload Lambda 
  to S3].Output.Package.FileName}"
```

Which breaks the YAML.

The previous 1.1 version does not do this and works as expected, so my current workaround is to tell my entire dev team to install the previous version and turn off auto update.

**Comment by Tchoupinax** [comment]
Same issue detected on my side :(

**Comment by eugene-marchanka** [comment]
Same here. Is there a way to disable it?

**Comment by longkai** [comment]
Hi, all, the latest version 2.2.0 has just released with a new option `lineWidth` which defaults to 0 and you can get rid of this issue.
