### ISSUE TITLE
Autoformat removes appended `0` making K8S manifests invalid

### ISSUE THREAD

**Issue by eugene-marchanka** [longkai/kubernetes-yaml-formatter#25]
I generate my manifests using Helm.

Before save:
![image](https://github.com/user-attachments/assets/e2280e41-8e95-4ff6-90f2-1e685302294f)

After save:
![image](https://github.com/user-attachments/assets/2c12f04a-e4d8-43b2-bf42-54a5c6756657)

This resulting in Kubernetes error:
```
Pod "mongodb-0" is invalid: [spec.volumes[2].configMap.defaultMode: Invalid value: 550: must be a number between 0 and 0777 (octal), both inclusive, spec.volumes[3].configMap.defaultMode: Invalid value: 755: must be a number between 0 and 0777 (octal)
```

Note: wrapping those octal numbers in `"` not an option. I generate manifests using Helm and can't afford to keep an 👁️ on everything this plugin autoformat on save

**Comment by longkai** [comment]
Hi, the v2 version default uses [YAML 1.2 schema](https://yaml.org/spec/1.2-old/spec.html#id2805071), which requires octal values to have an 0o prefix. So you should use `0o755`.

You can also set yaml directives at the beginning of the doc and that would use yaml 1.1 schema:

```yaml
%YAML 1.1
---
xxx: 0755
```

However, that would not work if multiple yaml documents in one file.

The yaml 1.2 and 1.1 schema almost compatible but still some corner cases. Though I could set a global settings default to `1.1` but it seems not that necessary?

How do you think about?

**Comment by eugene-marchanka** [comment]
I think that it would be nice to have an option to use different versions of the schema.
Is 1.2 backwards compatible with 1.1?

**Comment by eugene-marchanka** [comment]
@longkai Is there any updates on this?
I really need that functionality back and seems like your extension is the only extension currently maintained.
I tried to go over extension code base to find where I can set schema version myself and create a PR but have not found anything 😢

**Comment by longkai** [comment]
Hi, try upgrade the latest 2.3.0 version. There is a new option `better-yaml.documentOptions.version` which default to `1.2`. You can set to `1.1`.

Note this is a global option. Prefer use `0o` also each time you get yaml from k8s you actually got a decimal value.
