### ISSUE TITLE
2.0 upgrade add spaces in ranges

### ISSUE THREAD

**Issue by romainourgorry** [longkai/kubernetes-yaml-formatter#26]
Hello,

First of all thank you for this nice formatter which format my list as I want (not like prettier)

Between version 1.1.0 and 2.0.0 you added the range formatter, is it possible to disable it?

With 1.1.0
`valid_http_versions: [ "HTTP/1.1", "HTTP/2.0" ]`

With 2.0.0
`valid_http_versions: [  "HTTP/1.1", "HTTP/2.0"  ]`

I don't want to add the space at the beginning and the end of the range.

Thank you in advance for your answer

**Comment by longkai** [comment]
hello,

Range formatter only works when you select a range of code.

And the v2 version will only add *one* space at the beginning and the end.

What you want is `["HTTP/1.1", "HTTP/2.0"]`?

**Comment by romainourgorry** [comment]
Hello,

Yes this is exactly what I would like to do

**Comment by longkai** [comment]
Hello, the version 2.4.0 has been released which contains a new option `better-yaml.flowCollectionPadding` which default to `true`.

Set to `false` will give you that result.

**Comment by romainourgorry** [comment]
Thank you very much, it works perfectly.
