### ISSUE TITLE
Feature request: Configurable `include_document_start`

### ISSUE THREAD

**Issue by ajhall** [longkai/kubernetes-yaml-formatter#3]
`yamlfmt` includes a [setting for `include_document_start`](https://github.com/google/yamlfmt/tree/main/formatters/basic) to control whether documents should start with `---`. I'd like to be able to set this to `true`.

It looks like that would be fairly easy to implement in exactly the same way as `compact_sequence_indent`:
https://github.com/longkai/kubernetes-yaml-formatter/blob/main/src/extension.ts#L75-L95

**Comment by longkai** [comment]
1.1.0 has beed published to the marketplace and it contains this support.

**Comment by ajhall** [comment]
Thanks, this works perfectly! I made #4 to fix up the package.json to make it work with the settings page.
