### ISSUE TITLE
Incorrect settings declaration

### ISSUE THREAD

**Issue by karmicdude** [longkai/kubernetes-yaml-formatter#7]
`vscode 1.74.0-insider`
`Kubernetes YAML Formatter v1.1.0`

The registered settings show the settings without the prefix `kubernetes-yaml-formatter.`.

In vscode Settings extension names `Use Compact Sequence Indent` (?) with two check-boxed settings `Compact Sequence Indent` and `Include Document Start`.

![](https://imgur.com/UAwtPaE.png)

When the checkbox is enabled, json settings file gets settings without prefix `kubernetes-yaml-formatter.`, just i.e. `"includeDocumentStart": true,` and vscode thinks it's okay. But the settings don't work. But if i set manually `"kubernetes-yaml-formatter.includeDocumentStart": true,` settings works when I format file, but vscode thinks it's unknown and unused settings, dimming them.

**Comment by longkai** [comment]
Hi!

Sorry for the delay. I have fixed it in the v2 branch and it should release soon.

You have more controls for including directives in the output format.

**Comment by longkai** [comment]
The v2 version has been released on VSCode and fix this issue.

Give it a try!
